services:
  - type: web
    name: reachinbox-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_REDIRECT_URI
        sync: false
      - key: WORKER_CONCURRENCY
        value: 5
      - key: EMAIL_SEND_DELAY_MS
        value: 2000
      - key: MAX_EMAILS_PER_HOUR_PER_SENDER
        value: 200

  - type: worker
    name: reachinbox-worker
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/worker.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: WORKER_CONCURRENCY
        value: 5
      - key: EMAIL_SEND_DELAY_MS
        value: 2000
      - key: MAX_EMAILS_PER_HOUR_PER_SENDER
        value: 200
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
